### ISSUE TITLE
Flux and Sails.js

### ISSUE THREAD

**Issue by lance-anderson** [lynnaloo/yacht-rock#12]
I came across your project while googling trying to understand the overlap between Sails.js and Flux. I understand using React as the View engine with Sails. What isn't clear to me is how reasonable it is to use both Flux and Sails.js. I'm going to clone your project and play around with it but I was curious to know your thoughts on the matter and/or if you knew of anyone else using the two together and/or if you knew of any blogs or other references on the subject. thanks!

**Comment by lynnaloo** [comment]
This project started originally as my playground because I wanted to use React with Sails and I couldn't find any existing boilerplates. As I started using Flux more in some of my other applications, I added it here, but I haven't added any good use-cases for it since that update. But I mainly I use it to manage state over multiple React components. In this app, a good example would be for showing/hiding/changing the error message label I have on the main component. I'll try to beef this up a little in the coming week to show some better examples.

**Comment by lance-anderson** [comment]
Thank you. In your other apps that you have started using Flux do you also use Sails?

**Comment by lynnaloo** [comment]
No, I've only used it with a custom server-side implementation but the setup is pretty similar to what I've done here, but the API calls are to a custom route. I'm using jQuery in the `ApiHelper` here too which does the job for a quick implementation, but I need to clean that up too.

**Comment by lance-anderson** [comment]
Thanks again for the feedback. I noticed you also have a meteor project. I'm wrestling with using Sails+React/Flux or committing to Meteor for my next project. Curious if you have any input to add.

**Comment by lynnaloo** [comment]
I haven't used Meteor a ton, but I'll gladly give you my take on one versus the other based on my experience. It largely depends on the project you're working on.

One of the big things for me with Meteor is the fact that you're tied to using MongoDB. So, if you want the option to use some other database, then you'll definitely want to use Sails. That being said, I really like Meteor for smaller apps where I don't care about the data except to save and retrieve it quickly. You can also build an application really really quickly with Meteor because it has packages which give you a lot of things out of the box (ie: integration with other services like Twitter/Facebook). There's some "magic" that happens there that does a lot for you just by generating a new Meteor application. So, basically you can get a lot for free if you're willing to have your hands tied a bit with their package system and project setup.

If I'm writing more of an enterprise application, then I would choose Sails over Meteor. Most of that is because I want to get what I can for free, but to also keep a certain amount of control (less "magic") if I am going to need to scale later. I also want to be able to choose my database and MVC frameworks and swap them out when I feel like it.

That's about it in a nutshell :)

**Comment by lance-anderson** [comment]
That's super helpful. Thank you for taking the time to respond; I greatly appreciate it. I get a little sick to my stomach thinking about giving up the control to get some magic. There's always a tradeoff there. :smile:

**Comment by lynnaloo** [comment]
No problem. For teaching kids/teens how to build applications, Meteor has become my favorite tool to use. So I consider it my go-to for "quick-and-dirty" JavaScript applications that actual function really well.
